# Generated by Django 6.0.6 on 2026-09-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='chats/attachments/threads/'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatthread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='chats/attachments/rooms/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='roommessage',
            name='body',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
