# Generated by Django 6.0.8 on 2026-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_roommessage_attachment_alter_roommessage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='threadmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
