# Generated by Django 6.0.8 on 2026-09-26 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_roommessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatthread',
            name='user1_lte_user2',
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.CheckConstraint(condition=models.Q(('user1__lte', models.F('user2'))), name='user1_lte_user2'),
        ),
    ]
