# Generated by Django 6.0.8 on 2026-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chatthread_user1_lte_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
