# Generated by Django 6.0.6 on 2026-06-15 08:48

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=apps.users.models.User.user_directory_path),
        ),
    ]
