# Generated by Django 6.0.6 on 2026-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customsession'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friend_req',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='prevent_self_req',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
