# Generated by Django 6.0.8 on 2026-09-23 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 23, 16, 39, 42, 363483, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
