"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
import shutil

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'phonenumber_field',
    'treebeard',
    "tailwind",
    'social_django',
    "django_htmx",

    'apps.classes.apps.ClassesConfig',
    'apps.users.apps.UsersConfig',
    'apps.orgs.apps.OrgsConfig',
    'apps.theme.apps.ThemeConfig',

]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2', # Oauth Github
    'social_core.backends.google.GoogleOAuth2', # Oauth Google
    'django.contrib.auth.backends.ModelBackend',  # Default
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']
SOCIAL_AUTH_GITHUB_KEY = os.getenv('SOCIAL_AUTH_GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('SOCIAL_AUTH_GITHUB_SECRET')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = 'config.urls'

SESSION_ENGINE = "apps.users.models"

# Whenever a template is rendered with a request, a context is also returned. Imagine we are building an app where 
# we have to include the same data in every view we create. It is hard and prone to error right. This is where context 
# processors come in to play. context_processors contains a list of paths to callables which will return a dictionary to
# be merged with context of each view saving us the trouble of having to add the same data over and over again.


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

MAX_DEPTH = 5

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
 'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Read https://medium.com/django-unleashed/caching-in-django-with-redis-a-step-by-step-guide-40e116cb4540 on how to use caching
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': "redis://127.0.0.1:6379",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT':300
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# tailwind
TAILWIND_APP_NAME = "apps.theme"

NPM_BIN_PATH = shutil.which('npm')

# Social Auth
SOCIAL_AUTH_PIPELINE = [

    'social_core.pipeline.social_auth.social_details',

    'social_core.pipeline.social_auth.social_uid',

    'social_core.pipeline.social_auth.auth_allowed',

    'social_core.pipeline.social_auth.social_user',

    'social_core.pipeline.user.get_username',

    'social_core.pipeline.social_auth.associate_by_email',

    # Custom pipeline
    'apps.users.pipeline.get_user_type',

    'social_core.pipeline.user.create_user',

    'social_core.pipeline.social_auth.associate_user',

    'social_core.pipeline.social_auth.load_extra_data',

    'social_core.pipeline.user.user_details',
]

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30 # 30 days

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'users-dashboard'

AUTH_USER_MODEL = 'users.User'

# Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587

PASSWORD_RESET_TIMEOUT = 3600  # Valid for 1 hour

EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')

# Celery

# Take the jobs from redis
CELERY_BROKER_URL = "redis://127.0.0.1:6379"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True

TIME_ZONE = 'Asia/Kolkata'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# Absolute path of uploads which is /media/profile.png
MEDIA_ROOT = BASE_DIR / 'media'

# what is shown by browsers when we access those uploads like http://localhost/media/profile.png
MEDIA_URL = '/media/'

STATIC_URL = "static/"

# Global static directory. It is recommended to create app specific static dirs such as users/static/users/style.css
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# All static files are gathered using command collectstatic into STATIC_ROOT for deployment.
STATIC_ROOT = BASE_DIR / "staticfiles"