# Generated by Django 6.0.6 on 2026-07-20 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$', 'Only alphanumeric characters with spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(),
        ),
    ]
