# Generated by Django 6.0.6 on 2026-07-24 18:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_name_alter_class_slug'),
        ('orgs', '0007_alter_orginvitation_unique_invitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$', 'Only alphanumeric characters with spaces are allowed.')])),
                ('slug', models.SlugField()),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_class_name_inside_org',
        ),
        migrations.AddField(
            model_name='classroom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_classrooms', related_query_name='owned_classroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='parent_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', related_query_name='classroom', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='classmembership',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to='classes.classroom'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='members',
        ),
        migrations.RemoveField(
            model_name='class',
            name='org',
        ),
        migrations.RemoveField(
            model_name='class',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('parent_org', 'slug'), name='unique_class_name_inside_org'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
