# Generated by Django 6.0.6 on 2026-08-21 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classroom_remove_class_unique_class_name_inside_org_and_more'),
        ('orgs', '0008_alter_orgconfig_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_class_name_inside_org',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='parent_org',
            new_name='parent',
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_class_name_inside_org'),
        ),
    ]
