# Generated by Django 6.0.8 on 2026-10-01 15:34

import apps.classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_unique_class_name_inside_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=apps.classes.models.Classroom.classroom_directory_path),
        ),
    ]
