# Generated by Django 6.0.6 on 2026-07-06 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_class_slug_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='classmembership',
            name='unique_user_per_class',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(related_name='classrooms', related_query_name='classroom', through='orgs.ClassMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owned_classrooms', related_query_name='owned_classroom', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmembership',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Revoked')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_orgs', related_query_name='owned_org', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', related_query_name='classroom', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='classmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', related_query_name='classroom_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='unique_class_name_inside_org'),
        ),
        migrations.AddConstraint(
            model_name='classmembership',
            constraint=models.UniqueConstraint(fields=('user', 'classroom'), name='unique_class_membership'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_org_memberships', related_query_name='created_org_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', related_query_name='org_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='teachers',
            field=models.ManyToManyField(related_name='orgs', related_query_name='org', through='orgs.OrgMembership', through_fields=('org', 'teacher'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='class',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='class',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classmembership',
            name='is_active',
        ),
        migrations.CreateModel(
            name='OrgAdmin',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to='orgs.orgmembership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admins', related_query_name='created_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='orgmembership',
            constraint=models.UniqueConstraint(fields=('teacher', 'org'), name='unique_org_membership'),
        ),
    ]
