# Generated by Django 6.0.6 on 2026-07-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_orgmembership_remove_class_unique_class_slug_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_class_name_inside_org',
        ),
        migrations.RemoveConstraint(
            model_name='classmembership',
            name='unique_class_membership',
        ),
        migrations.RemoveField(
            model_name='classmembership',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassMembership',
        ),
    ]
