# Generated by Django 6.0.6 on 2026-07-14 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_remove_class_unique_class_name_inside_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='teachers',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_orgs', related_query_name='created_org', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgadmin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_admins', related_query_name='created_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='orgmembership',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_org_memberships', related_query_name='created_org_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrgConfig',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='orgs.organization')),
                ('type', models.CharField(choices=[('C', 'College'), ('S', 'School'), ('T', 'Tuition')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_orgs', related_query_name='owned_org', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
