# Generated by Django 6.0.6 on 2026-07-16 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_remove_organization_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed with no spaces.')]),
        ),
        migrations.AlterField(
            model_name='orgconfig',
            name='type',
            field=models.CharField(choices=[('CL', 'College'), ('SC', 'School'), ('TN', 'Tuition'), ('CG', 'Coaching'), ('CP', 'Company'), ('OT', 'Other')], max_length=2),
        ),
    ]
