# Generated by Django 6.0.6 on 2026-07-20 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_alter_organization_name_alter_orgconfig_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$', 'Only alphanumeric characters with spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='orgconfig',
            name='type',
            field=models.CharField(choices=[('CL', 'College'), ('SC', 'School'), ('TN', 'Tuition'), ('CG', 'Coaching'), ('OT', 'Other')], max_length=2),
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', related_query_name='sent_invitation', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', related_query_name='invitation', to='orgs.organization')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', related_query_name='received_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('to_user', 'org'), name='unique_invitation')],
            },
        ),
    ]
