# Generated by Django 6.0.6 on 2026-07-24 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_organization_name_alter_orgconfig_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='orginvitation',
            name='unique_invitation',
            constraint=models.UniqueConstraint(fields=('to_user', 'org'), name='unique_invitation', violation_error_message='You already sent an invitation to this user'),
        ),
        migrations.AlterConstraint(
            model_name='orgmembership',
            name='unique_org_membership',
            constraint=models.UniqueConstraint(fields=('teacher', 'org'), name='unique_org_membership', violation_error_message='Teacher is already a member of this organization.'),
        ),
    ]
