# Generated by Django 6.0.6 on 2026-07-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_orginvitation_unique_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgconfig',
            name='type',
            field=models.CharField(choices=[('CL', 'College'), ('SC', 'School'), ('TN', 'Tuition'), ('CG', 'Coaching')], max_length=2),
        ),
    ]
